language: node_js
node_js:
- '5.11'
sudo: required
notifications:
  email:
  - andygoestohollywood@gmail.com
env:
  global:
  - PORT=4000
  - NODE_ENV=travis
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: DxGESrn37c6lqbtOqa5AQ92urpRENubC5OXGScpSQuNysEbfMMd2SQYP69iM33bl368K12MaGNCuCDFbRer2n1fheNdon9TmkDSM/L5HQ4yqyx85wikKYlgXxgRT9sItJxlYHZ/SCyh8/aIGmmiAQCy+0c1o+WBbmSIFd9E9A2ifmXKlLJpe1XQzttc7K5uNj9p+INMWKbFIXCu93YrEO3rntHGqiT8OrVSYZinM0uvIqTMlYD5J81OK4oECy8H3CGG1efEldQLGEb6yKD2RuN3wJqHehTK2kRxEnUqZHP5+eJ44KzJGeAmyo+ZXVrLnthJ4EhKWPIfLHwxHZP5kTGqPXU9tOlcUOv5IfSpMH/s1dD4DVXqP5U3u8Jd04XYhWhY5dmb70GEhkWdNG7T/ZCfnXaRotIOmGxy8JLiJqsqnULSE9EcQ8MaZzYPAxgRnGv26Vj0tFn1K1kQCuBvXcwxN+rzkrPqBJJjqtmMHPQksIrT+oQoiCd2bytnvEv9EIdPk/SFqNwpDonlZy5eRphgZGUnhrQ25NU5fzyKtKkU77gcefL3cj8yuP3G5S4ctBiKb3Gbrf3Fv8BAj/T1tHaPyL3aHcWDpxrOMqNeZ0k4F6NeHuL8sq4A01nPx3DBksfBJcmidj5I09eaeaI/Jn3zza/OgFWBVvJ6BBvGZeDM=
  - secure: Bn1kG90abIbMULFcTtPGpjyzRSJ45FoBbmbLVbkjEqwXx+6Gu43Q0qUr1+xLUAbcjBbOs9eCFq9LzBOaLiRrwl49n393JZPeL82zq3Ywtx0uOGowj4pj0uNOHpBOBp155Wst9jq8wJwWjKI64i9xrewHJ0xYCvybERWnae7bErrEdg9k/eH62LrkuwtjZwO3X/uOyPzqYtGjHOCnv0g/JvjdVmgUiIyzYf0VGBVqy5IMHLquzqCnFwxqWj4x65MFUMZ9QpqAx5HmSB65IVLYBPJynVCcwL9tMeH6eG3bp1pGThFfecY9Z90s4mD3uvZO3KxOnj9JDT0buQhjUwyZQfQBIBRRaW1It55vEfdPwQnQImLbYProfZ5QW5kG78cFiQa14m8bVfKeoU1ufCD8HTsNzzOtktG91IVbskkmKfj/AHRwGrMSCSmuVZ+XCLeoxGkFXHfNN/RCOlNwHUDplGotCn+MNdb+nb/KcjVYfwwd6MrIicYXPIqn4SRi+nzeFREDjcutI95YsTvqpeOUMNmceo92MhOapzGUQp7Mh0UuRjDipmXJBeKzgeCN/0Krbbe8RFNYXbEoZAgzfHJ0PhWaEe/8GGvIWWrd391vM44Apw9gwt1d/Fet/ZtzHO5X+ejRdPHvlmZ7W8KQzl05eKVJNnolbMQHMK5CvlBNqqQ=
addons:
  browserstack:
    username: hayesmaker
    access_key:
      secure: z5AyOXEQiuyfMC8DVYFiYSbXVCqEPZq8W6dq6kmyPOdwjgqdqtmeLzhqntcrpx3KBprpgtX/oCsbA+YaLZC0n91rtXzXkYlq03G2BDBNnmTYhQZbOL6OpGzL4juWmu8GdJEgTApT0yCDIVEQk592K1P7U4K/09DP/7wXZ9vmBhi7PQEbVKHwKY+VYGbuH9U5omrfRlLcg9jkxa/Y1QsxwnKNhasN5ywupnXKZFPGkr/9ZX13iuoQWEKoNWlqfjiFBqk+8FF2IiNwmb0TSDRoyisytcGs6X/k5xhzh8iNC1YJ9gJIM3U/UJG78t06qI+qYZzaTNwhWNR5IuH0eo0W4Em3eQtzwZOZce0tfBkw/PBxrfIeoEvyROdlsk/uYBj7P+LpOuXkcujs7VpRUPbKlxAKdiiCeEfSDD+S5xfgVpOhKjeiYBfL7PR4yAyiYJHZq+I2dV+L9lcbc1vy8YwHBujKqLMzQCi6njM/efA+LG4MKOPC0gFgQuUj3S2iFurROMQqU53RDIG0HIIvmpi8whETK6PlmI5J9aCZEQ+J+LjUYP7UZzBBAVc6NWf0Oe+cxWklMLLX9FirDJprRMKsjEf044sK7kh/K3+8yiv66kwlpGnOjB/G0Kgrdu7JfESmCvYmkRud29/NRdAm5lWJo5N+UKIKEW8zJj0r9OMWdL4=
before_script:
- npm run build
script:
- npm start
- npm run test:basic
after_script:
- pm2 stop all
deploy:
  provider: heroku
  api_key:
    secure: wnDK7ur0wokD6JqZKTA0tIPDISYVIR/ZgYKEse/SRplhe35nlsYpGGp4HQ88R7i4xpJ+6OV49g8YgrKjX1PyXx1SN9M1/2B8PKkkFm6jRreXt4F3rWKk67g8Y+vgndb7MrGbizvHhj97bOk5C+chEJchkFKla2w3n5flEpKWkROme5KSE1903yc6AUxEl35iZbW+GAok68I+OQAYIVtFogFeyow3BgEbJ+Q6YgeeumS6OOtyAPCCkUVzDKRfcGyg3UR7W97o4UvCcHHS4h6uESoXGMA0TfL9rQoGQoxU7B1L1R6t00cugZrPNqUrDCRCfx8hhhCNWOMvP97TODrQm58IoCCXteINzMFmEWF0/dss2EByRxxcO9EWb2f9/xBWNdISGS4Gjsi23ZyjEhhZNaAwWUC83M2nQIK4EWnj7vub0oRFfb2nDxMQY/BtruUAOZXq/veZ7vvqwRiNqY/Tn9z6kzFOFwe+6PrF3iWhPyGurcp9OelhRYF0itiU8dcKlbDzoEQf6803MSO81Fb+FxRS4EFCgiKEzyVeQ1YmmJCwrHlWfVFbt3vUCCaUa27blAqffCPgEmF+uFClffFOiPKY+xmeKY71MgsVs75m6OHtWbjqjT1CQdwgPMqU1b56PX9OtweE/ZZeaIP+1Uq82oWvIIFumKZdnLNbPIfvf+o=
